### ISSUE TITLE
Exceed Limit

### ISSUE THREAD

**Issue by Jkaiser223** [IAHispano/Applio-Plugins#9]
Hey i understand this require an API to use but can you assist me in finding free alternatives to this issue? I like this tool, but in my current position, i can't afford to get a key, so what can i do?

Also why isn't adam part of the voice selections? 
![opera_AkdqzQOTJR](https://github.com/user-attachments/assets/55f05c71-0afa-4d58-9f90-116ff196c8c4)
![cmd_ZObyI5CIqD](https://github.com/user-attachments/assets/1380ae94-6edb-427c-a6c4-9d59a7cc9ee7)

**Comment by blaisewf** [comment]
use the Applio's TTS
